services:

  app:
    build:
      context: ../../
      dockerfile: src/docker/app.Dockerfile
    image: scs-app:v7
    ports:
      - "8080:8080"
    environment:
      spring.kafka.bootstrap-servers: kafka:29092
      spring.cloud.stream.bindings.consumer-in-0.destination: input
      spring.cloud.stream.bindings.consumer-in-0.group: consumer
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
